---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 59794002-Qgpc2QOiHMTVEQ7oyYqgC21apwiIbcG1ZI1youpXA
:oauth_secret: rfibbIp9PDiT7L1UQtgFndLBFtrLVWudWyAKthI0c
