---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 59792784-CPQJFIXDcudCpxIcAlbPTo6btZkFIzjxikAsKOT2Y
:oauth_secret: yiZuChK1cfU1HtUo9FpnB77gnDlnsRD4nHMfQSow
